language: c
sudo: false
cache:
  directories:
    - /home/travis/devkitPro

before_install:
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - mkdir -p $DEVKITPRO
  - cd $DEVKITPRO
  - wget -N https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitARMupdate.pl

install:
#  - sudo perl devkitARMupdate.pl
  - cd $DEVKITPRO
  - perl devkitARMupdate.pl
  - cd $TRAVIS_BUILD_DIR

script: make
