language: c

addons: 
  apt: 
    packages: 
      - p7zip-full
      - zip
      - pacman

before_cache:
  - export DEVKITPRO=/opt/devkitPro
  - export DEVKITPPC=${DEVKITPRO}/devkitPPC
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export DEVKITPPC=${DEVKITPRO}/devkitPPC
  - export DEVKITPSP=${DEVKITPRO}/devkitPSP  
  - export DEVKITA64=${DEVKITPRO}/devkitA64
  - rm -rf $DEVKITPRO/*.7z
  - rm -rf $DEVKITPRO/*.bz2
  - rm -rf $DEVKITPRO/examples
  -

before_install:
  - export DEVKITPRO=/opt/devkitPro
  - export DEVKITPPC=${DEVKITPRO}/devkitPPC
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export DEVKITPPC=${DEVKITPRO}/devkitPPC
  - export DEVKITPSP=${DEVKITPRO}/devkitPSP  
  - export DEVKITA64=${DEVKITPRO}/devkitA64

install:
  - cd $TRAVIS_BUILD_DIR
  # install pacman (in case it's not already there)
  - sudo apt install pacman
  - sudo find / -name pacman*
  - find / -name pacman*
  
  # possible fix for pacman-key command not found error?
  # See https://github.com/github/ghfw-build-extra/pull/17/commits/e071e678ea5fc9eb1f9e0976dff8629cbcbac273
  # - sudo mkdir /tmp
  - sudo pacman-key --init
  # obtain the debian package
  - sudo wget -N https://github.com/devkitPro/pacman/releases/download/v1.0.0/devkitpro-pacman.deb
  # import the key for the package
  - sudo pacman-key --recv-keys F7FD5492264BB9D0
  - sudo pacman-key --lsign-key F7FD5492264BB9D0
  # install the package
  - sudo dpkg -i devkitpro-pacman.deb 
  ### Add the following lines to /etc/pacman.conf
  - echo "[dkp-libs]"                                             | sudo tee -a /etc/pacman.conf
  - echo "Server = http://downloads.devkitpro.org/packages"       | sudo tee -a /etc/pacman.conf
  - echo "[dkp-linux]"                                            | sudo tee -a /etc/pacman.conf
  - echo "Server = http://downloads.devkitpro.org/packages/linux" | sudo tee -a /etc/pacman.conf
  # install the package keyring...
  - sudo pacman -U https://downloads.devkitpro.org/devkitpro-keyring-r1.787e015-2-any.pkg.tar.xz
  # update the pacman databases
  - sudo pacman -Syy
  # verify by manually listing the packages
  - sudo packman -Sl dkp-libs
  # install the package using the predefined group:
  - sudo packman -S switch-dev
  # list the installed devkitpro...
  - cd $TRAVIS_BUILD_DIR
  - ls --color=auto -l --almost-all --classify --group-directories-first --indicator-style=slash --recursive $DEVKITPRO

script: make
