language: c

before_install:
  - export DEVKITPRO=/opt/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - sudo mkdir -p $DEVKITPRO
  - cd $DEVKITPRO
  - sudo wget -N https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitA64update.pl

install:
  - cd $DEVKITPRO
  - sudo perl devkitARM64update.pl
  - cd $TRAVIS_BUILD_DIR

script: make
