language: c

before_install:
  - export DEVKITPRO=/opt/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - sudo mkdir -p $DEVKITPRO
  - cd $DEVKITPRO
  - sudo wget https://raw.githubusercontent.com/Selver-gba/installer/TmpDebug/perl/devkitA64update.pl

install:
  - cd $DEVKITPRO
  - sudo perl devkitA64update.pl
  - cd $TRAVIS_BUILD_DIR

script: make
