language: c

before_install:
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - sudo mkdir -p $DEVKITPRO
  - cd $DEVKITPRO
  - sudo wget https://raw.githubusercontent.com/Selver-gba/installer/TmpDebug/perl/devkitA64update.pl

install:
  - cd $DEVKITPRO
  - sudo perl devkitA64update.pl
  - cd $TRAVIS_BUILD_DIR
  - ls --color=auto -l --almost-all --classify --group-directories-first --indicator-style=slash --recursive $DEVKITPRO
  - ls --color=auto -l --almost-all --classify --group-directories-first --indicator-style=slash --recursive $TRAVIS_BUILD_DIR
  

script: make
